LARGURA = 1000
ALTURA = 800

NUM_PECAS_DAMAS = 12
NUM_PECAS_XADREZ = 16

BLACK = (0,0,0)
GOLDEN_BLACK = (83,84,46)
GRAY = (80,80,80)
DARK_GRAY = (40,40,40)
WHITE = (255,255,255)
GOLDEN_WHITE = (174,176,106)

FONTE_PRIN = None

PATH_SPRITE_BRANCA = "Main/Sprites/PECA_BRANCA.png"
PATH_SPRITE_PRETA = "Main/Sprites/PECA_PRETA.png"

PATH_SPRITE_PEAO_BRANCO = "Main/Sprites/Peao.png"
PATH_SPRITE_TORRE_BRANCO = "Main/Sprites/Torre.png"
PATH_SPRITE_CAVALO_BRANCO = "Main/Sprites/Cavalo.png"
PATH_SPRITE_BISPO_BRANCO = "Main/Sprites/Bispo.png"
PATH_SPRITE_REI_BRANCO = "Main/Sprites/Rei.png"
PATH_SPRITE_RAINHA_BRANCO = "Main/Sprites/Rainha.png"

DICT_PATH_SPRITE = {
    0 : (PATH_SPRITE_BRANCA, PATH_SPRITE_PRETA),
    1 : (PATH_SPRITE_BRANCA, PATH_SPRITE_PRETA),
    2 : (PATH_SPRITE_PEAO_BRANCO, PATH_SPRITE_PEAO_BRANCO),
    3 : (PATH_SPRITE_TORRE_BRANCO, PATH_SPRITE_TORRE_BRANCO),
    4 : (PATH_SPRITE_CAVALO_BRANCO, PATH_SPRITE_CAVALO_BRANCO),
    5 : (PATH_SPRITE_BISPO_BRANCO, PATH_SPRITE_BISPO_BRANCO),
    6 : (PATH_SPRITE_RAINHA_BRANCO, PATH_SPRITE_RAINHA_BRANCO),
    7 : (PATH_SPRITE_REI_BRANCO, PATH_SPRITE_REI_BRANCO)
}
